# permissions for end users to edit ovirts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ovirt-editor-role
rules:
- apiGroups:
  - agents.kemo.network
  resources:
  - ovirts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agents.kemo.network
  resources:
  - ovirts/status
  verbs:
  - get
