# permissions for end users to view ovirts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ovirt-viewer-role
rules:
- apiGroups:
  - agents.kemo.network
  resources:
  - ovirts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - agents.kemo.network
  resources:
  - ovirts/status
  verbs:
  - get
