# permissions for end users to edit virtualbmcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualbmc-editor-role
rules:
- apiGroups:
  - agents.kemo.network
  resources:
  - virtualbmcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agents.kemo.network
  resources:
  - virtualbmcs/status
  verbs:
  - get
