# permissions for end users to view virtualbmcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualbmc-viewer-role
rules:
- apiGroups:
  - agents.kemo.network
  resources:
  - virtualbmcs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - agents.kemo.network
  resources:
  - virtualbmcs/status
  verbs:
  - get
